### ISSUE TITLE
Can the calendar, battery percentage, and VPN status display be added?

### ISSUE THREAD

**Issue by varjay** [Lessica/TrollSpeed#1]
Jailbreaking is for these functions, but the storage space after 15.4.1 jailbreak is too small.
Can the calendar, battery percentage, and VPN status display be added?
Thanks.

**Comment by Lessica** [comment]
Yes, it is for **you** to do that.

**Comment by mailinglists35** [comment]
we are innocent users, is it possible for you @Lessica to add them?

for me it would be very useful to have speed (unified), time and battery numeric level.

I know it is abusing and hijacking the original goal of the app, but looks like the only way to see battery level and time when apps hide the status bar :-(

**Comment by dlevi309** [comment]
Just wanted to say thanks for deciding to open source this, it’s a really interesting project and I was wondering how it was done 👍

**Comment by Lessica** [comment]
TrollSpeed is just a network speed widget: I don't want to add other features to it.

So I open-sourced this repo for everyone who want to build their own floating window "tweaks".
