### ISSUE TITLE
Dynamo island obstructing hud

### ISSUE THREAD

**Issue by PIPPOAKERFILE** [Lessica/TrollSpeed#10]
The dynamic island obstructs the hud

**Comment by PIPPOAKERFILE** [comment]
![image](https://github.com/Lessica/TrollSpeed/assets/84002808/2a27df5b-8888-43d6-9ea6-a5e4f49dc755)

**Comment by PIPPOAKERFILE** [comment]
![image](https://github.com/Lessica/TrollSpeed/assets/84002808/d6b40b92-9187-4f09-bc01-f1bc27baa804)

**Comment by Lessica** [comment]
Which device model?

**Comment by PIPPOAKERFILE** [comment]
iPhone X

**Comment by PIPPOAKERFILE** [comment]
Will probably be the same on my iPhone 14

**Comment by PIPPOAKERFILE** [comment]
Gonna try that when I get home

**Comment by Lessica** [comment]
> The dynamic island

iPhone X? The dynamic island?

**Comment by PIPPOAKERFILE** [comment]
Yea

**Comment by Lessica** [comment]
> Yea

Well, I won't adjust it's position for a fake Dynamic Island...

**Comment by PIPPOAKERFILE** [comment]
In gonna try it on an iPhone 14 in a few hours

**Comment by PIPPOAKERFILE** [comment]
@Lessica Same problem using an iPhone 14 pro

**Comment by Lessica** [comment]
> @Lessica Same problem using an iPhone 14 pro

Try the latest version?

**Comment by PIPPOAKERFILE** [comment]
Nope

**Comment by PIPPOAKERFILE** [comment]
Did not work

**Comment by Lessica** [comment]
> Did not work

Full screenshot with your iOS version and device model, please.

**Comment by PIPPOAKERFILE** [comment]
![image](https://github.com/Lessica/TrollSpeed/assets/84002808/2afcd670-ebb3-4928-931c-284c1b8428a4)

**Comment by PIPPOAKERFILE** [comment]
![image](https://github.com/Lessica/TrollSpeed/assets/84002808/80433c04-7e86-40c4-9472-3d7b645d65a1)![image](https://github.com/Lessica/TrollSpeed/assets/84002808/58627abf-c4ef-415a-bd93-4b81ce389f27)

**Comment by PIPPOAKERFILE** [comment]
@Lessica

**Comment by Lessica** [comment]
> ![image](https://private-user-images.githubusercontent.com/84002808/291012876-80433c04-7e86-40c4-9472-3d7b645d65a1.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3ODc2MzksIm5iZiI6MTcwMjc4NzMzOSwicGF0aCI6Ii84NDAwMjgwOC8yOTEwMTI4NzYtODA0MzNjMDQtN2U4Ni00MGM0LTk0NzItM2Q3YjY0NWQ2NWExLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwNDI4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTY5NDY1YTQwMTBlYjlmYzUwZjdhOWM1NTNkMWNmZGYwNDNhM2VlOWQxYmIyMTA1MzdmMGNiZWE5ZDFlYjRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4j41f6q-2LdXPsRToRkAMvew8dqlxcIiEU-CtsW1VZA)![image](https://private-user-images.githubusercontent.com/84002808/291012882-58627abf-c4ef-415a-bd93-4b81ce389f27.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3ODc2MzksIm5iZiI6MTcwMjc4NzMzOSwicGF0aCI6Ii84NDAwMjgwOC8yOTEwMTI4ODItNTg2MjdhYmYtYzRlZi00MTVhLWJkOTMtNGI4MWNlMzg5ZjI3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwNDI4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTllOTgxNDNkOTUzMmFmN2UwMjhiOGIyOWVmNDQ2NGVjODg4OTYxYWJiNWE0MDg3ZTc3ZDkzODI4MjdmNDk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZYT7WtGqER1_Y2TtrKnWbd1ieIf1al0QjtHM-oisTTY)

Well, I need a FULL screenshot with light background to measure the correct distance. Please.

**Comment by PIPPOAKERFILE** [comment]
Okay wait a sec

**Comment by PIPPOAKERFILE** [comment]
![image](https://github.com/Lessica/TrollSpeed/assets/84002808/0156a24a-b6f8-4ddd-a461-7f629a920dd7)

**Comment by PIPPOAKERFILE** [comment]
Here is where it is rn

**Comment by PIPPOAKERFILE** [comment]
I simply made a screen setter as wallpaper and got a screen without nothing on the island

**Comment by PIPPOAKERFILE** [comment]
@Lessica ?

**Comment by Lessica** [comment]
> ![image](https://private-user-images.githubusercontent.com/84002808/291054892-0156a24a-b6f8-4ddd-a461-7f629a920dd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NjE5OTEsIm5iZiI6MTcwMjk2MTY5MSwicGF0aCI6Ii84NDAwMjgwOC8yOTEwNTQ4OTItMDE1NmEyNGEtYjZmOC00ZGRkLWE0NjEtN2Y2MjlhOTIwZGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA0NTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YTdkZDk0NmVlMWE3NmFjYjJkZTIwMWMzZmMxOTQ1YWM1NGFhNGU2YTcyYjI3ZDI1YzA1YmJiODZlNWI2MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2N68fEdqTtBlicwyzEo1red78yTljosGHzZ7euiJiQc)

The screenshot seems incorrect, wait for other screenshots.

**Comment by Lessica** [comment]
I did not receive any other's screenshots like this. If anyone have the same problem, comment on this issue and I will re-open this and investigate into the layout issues.
