### ISSUE TITLE
HUD does not stay permanently

### ISSUE THREAD

**Issue by fregattegh** [Lessica/TrollSpeed#11]
I am aware of the fact that iPhone ios kicks off applications after some time but was under the impression that this app might stay permanently. I am on IP 14 pro ios 16.2 and TrollSpeed stays about 8 hours. Any chance to make it stay permanently.
Apart from that I love TrollSpeed!!!

**Comment by 21mtd** [comment]
Having the same issue on 14 pro max 16.2, but its been okay after I let it run in background instead of killing it, also turning off Always On Display

**Comment by Lessica** [comment]
This is a known issue but I can't find a reliable way to solve it. Jetsam is not very easy to bypass :-/

**Comment by fregattegh** [comment]
Thanks for coming back to this “challenge”.

Maybe as an interims solution it would be good to have TrollSpeed with a preference setting/switch “Open HUD after starting TrollSpeed without pressing the OPEN HUD button”.
This way we can set up a Shortcut “open TrollSpeed daily at a a specific time”  to push keeping it open.

Thanks also for the hint to switch off “Always on Display” and letting it run in the background.

Just an idea from a non programmer point of view.

Many thanks!!

**Comment by Lessica** [comment]
I believe this was fixed in [v1.9.3](https://github.com/Lessica/TrollSpeed/releases/tag/v1.9.3), please try that.

**Comment by fregattegh** [comment]
Wow! You found the issue. Many thanks; installed about 12 hours ago and since than the SpeedWindow keeps staying. Never thought that it was possible to circumvent the Apple rules (kicking off after some time) for an app. tnx !!

**Comment by fregattegh** [comment]
... still running; many thanks! issue solved!

**Comment by Lessica** [comment]
> ... still running; many thanks! issue solved!

However, the HUD process will be terminated when there is an extreme shortage of RAM.
