### ISSUE TITLE
What is Pass-through and Keep In-place?

### ISSUE THREAD

**Issue by 21mtd** [Lessica/TrollSpeed#12]
I've tried turning them on and off (and restart the HUD) but I dont notice any differences. Can anyone give me more specific comparison? 
Thanks

v1.9.2
14 Pro Max 16.2

**Comment by Lessica** [comment]
## Pass-through
If it's ON, the HUD will simply ignore any touch gestures.

## Keep In-place
If it's ON, the HUD will respond to TAP gesture and show you the total network traffic since the last boot, for a period of time.  
Or, you can tap and drag the HUD vertically.
