### ISSUE TITLE
Trollspeed Problems with usage

### ISSUE THREAD

**Issue by saltwest** [Lessica/TrollSpeed#13]
iPhone 12PRO，IOS16.5，After logging out, the status bar floating window disappears. When opening the app, it shows that the floating window is closed, indicating that it is already open

**Comment by saltwest** [comment]
![image](https://github.com/Lessica/TrollSpeed/assets/153748218/d04efbee-df6e-46e0-815c-e5d74041d107)

**Comment by Lessica** [comment]
看不大懂你描述的问题，说点中国话吧。

**Comment by saltwest** [comment]
12PRO，16.5系统，注销重启手机悬浮窗会消失，但是APP里面是开着的，要进APP里面关闭悬浮窗再打开才可以

**Comment by Lessica** [comment]
> 12PRO，16.5系统，注销重启手机悬浮窗会消失，但是APP里面是开着的，要进APP里面关闭悬浮窗再打开才可以

你都注销重启了，不能指望悬浮窗如此坚挺，毕竟不是越狱。

**Comment by saltwest** [comment]
好的，谢谢

**Comment by Lessica** [comment]
这个问题已经在 v1.9.5 中得到修复。

**Comment by saltwest** [comment]
厉害了👍🏻😂😂

**Comment by Lessica** [comment]
> 厉害了👍🏻😂😂

主要我意识到你说的注销指的是杀掉 backboardd 而不是只杀掉 SpringBoard。杀掉 backboardd 窗口管理服务确实会把悬浮窗窗口干掉。这个时候需要悬浮窗进程自行重启一下。
