### ISSUE TITLE
尺寸放大不生效

### ISSUE THREAD

**Issue by KiritoGuugk** [Lessica/TrollSpeed#16]
设备ipadpro m1
系统17.0
trollspeed版本 1.9.5
点击尺寸的放大后不显示正常的网速，过2秒后自动变回小尺寸且网速显示正常

录屏如下

https://github.com/Lessica/TrollSpeed/assets/35999227/e6eb11ac-c89f-40a8-a859-1330d002e5a5

**Comment by Lessica** [comment]
较大尺寸只会增加 1pt 的字号，不会非常明显，所以你看不出来 —— 和点击放大的效果是两码事。
点击放大时会显示本次开机后使用的总流量。

**Comment by Lessica** [comment]
Duplicate of #15

**Comment by Lessica** [comment]
![截屏2023-12-27 12 30 58](https://github.com/Lessica/TrollSpeed/assets/5410705/6299d2b5-9373-4cfe-b61e-2597f46e5ade)
