### ISSUE TITLE
Option to hide the widget when taking screenshot

### ISSUE THREAD

**Issue by yur1xpp** [Lessica/TrollSpeed#18]
Not sure if this is achievable in TrollStore environment, but Assistive Touch button able to automatically hid itself during the taking of screenshot. If it's possible, it would be a very useful addition to this amazing tweak/app.

**Comment by Lessica** [comment]
Assistive Touch is able to achieve that so I'm sure it's possible.

**Comment by Lessica** [comment]
This feature is implemented in [v1.9.6](https://github.com/Lessica/TrollSpeed/releases/tag/v1.9.6). Enjoy it!

**Comment by yur1xpp** [comment]
That's super awesome! Thanks for much for your time on that!!
