### ISSUE TITLE
I don’t see your plist file in the /Library/LaunchDaemons path on a non-rooted device, but I see that there is a plist file in the /Library/LaunchDaemons path on your source code. Why?

### ISSUE THREAD

**Issue by QuiYou** [Lessica/TrollSpeed#19]
I don’t see your plist file in the /Library/LaunchDaemons path on a non-rooted device, but I see that there is a plist file in the /Library/LaunchDaemons path on your source code. Why?

**Comment by Lessica** [comment]
因为 TrollSpeed 同一套代码支持有根/无根越狱和巨魔，共三个版本。在越狱版本中，TrollSpeed 悬浮窗进程在 `/Library/LaunchDaemons` 下注册为守护进程启动，以实现更稳定的保活；而在巨魔版本中，通过 App spawn 来启动悬浮窗进程，无法也无需在 `/Library/LaunchDaemons` 下提供守护进程配置。

**Comment by QuiYou** [comment]
哦怪不得。但是我是使用的Xcode开发您这个工程干起来挺麻烦的今天我观察了一晚上发现挺纳闷的我就说怎么在越狱设备上拥有plist在没有越狱设备上却找不到





------------------ Original ------------------
From: i_82 ***@***.***&gt;
Date: Fri,Jan 19,2024 0:01 PM
To: Lessica/TrollSpeed ***@***.***&gt;
Cc: Laote ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Lessica/TrollSpeed] I don’t see your plist file in the /Library/LaunchDaemons path on a non-rooted device, but I see that there is a plist file in the /Library/LaunchDaemons path on your source code. Why? (Issue #19)





 
因为 TrollSpeed 同一套代码支持有根/无根越狱和巨魔，共三个版本。在越狱版本中，TrollSpeed 悬浮窗进程在 /Library/LaunchDaemons 下注册为守护进程启动，以实现更稳定的保活；而在巨魔版本中，通过 App spawn 来启动悬浮窗进程，无法也无需在 /Library/LaunchDaemons 下提供守护进程配置。

**Comment by Lessica** [comment]
没有提供 Xcode 项目。建议使用 vscode + theos + clangd 环境开发。

**Comment by QuiYou** [comment]
我看看能不能整到Xcode上因为我的程序要用到Xcode才行之前使用的无声音乐文件的方式不太好





------------------ Original ------------------
From: i_82 ***@***.***&gt;
Date: Fri,Jan 19,2024 1:16 PM
To: Lessica/TrollSpeed ***@***.***&gt;
Cc: Laote ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Lessica/TrollSpeed] I don’t see your plist file in the /Library/LaunchDaemons path on a non-rooted device, but I see that there is a plist file in the /Library/LaunchDaemons path on your source code. Why? (Issue #19)





 
没有提供 Xcode 项目。建议使用 vscode + theos + clangd 环境开发。

**Comment by QuiYou** [comment]
不过你可以的话帮我创建一个也行哈哈我给你费用





------------------ Original ------------------
From: i_82 ***@***.***&gt;
Date: Fri,Jan 19,2024 1:16 PM
To: Lessica/TrollSpeed ***@***.***&gt;
Cc: Laote ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Lessica/TrollSpeed] I don’t see your plist file in the /Library/LaunchDaemons path on a non-rooted device, but I see that there is a plist file in the /Library/LaunchDaemons path on your source code. Why? (Issue #19)





 
没有提供 Xcode 项目。建议使用 vscode + theos + clangd 环境开发。

**Comment by Lessica** [comment]
> 不过你可以的话帮我创建一个也行哈哈我给你费用
> […](#)

可以啊，只要是不违反中国大陆法律的需求。可以邮件详谈：82flex@gmail.com

**Comment by QuiYou** [comment]
我看到你有3个这些参数。但是我没有看到他们是如何触发的。特别是-hud他是在plist里面设置为true巨魔您昨天说没有用到plist他是如何被触发的呢
我不知道写的是否正确，因为我把越狱部分和无根部分没有写入到我的工程。可以的话我邮件附加了一个Demo工程您可以帮我修改一下守护进程吗












------------------ Original ------------------
From: i_82 ***@***.***&gt;
Date: Fri,Jan 19,2024 4:28 PM
To: Lessica/TrollSpeed ***@***.***&gt;
Cc: Laote ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Lessica/TrollSpeed] I don’t see your plist file in the /Library/LaunchDaemons path on a non-rooted device, but I see that there is a plist file in the /Library/LaunchDaemons path on your source code. Why? (Issue #19)





  
不过你可以的话帮我创建一个也行哈哈我给你费用
 …
  
***@***.***
