### ISSUE TITLE
大佬为什么会出现 ld: framework not found BackBoardServices

### ISSUE THREAD

**Issue by qqwq122825** [Lessica/TrollSpeed#21]

**Comment by Lessica** [comment]
很少有人能准确地描述清楚这类问题的原因，所以我详细回复一下。

## 问题原因

https://github.com/Lessica/TrollSpeed/blob/aaeb96b5e4b9f28cb6d2726466525eb62fc2dd70/Makefile#L2

上述片段中的 **latest** 表明 Xcode 将在内置 SDK 路径 `$(xcode-select -p)/Platforms/iPhoneOS.platform/Developer/SDKs` 和 `$THEOS/sdks` 中选取一个最新的 SDK 版本来查找所需的动态链接库插桩，即 `.tbd` 文件。你可以排查下这两个目录，如下所示：

```bash
$ ls $THEOS/sdks
AppleTVOS10.2.sdk          iPhoneOS11.4.sdk
AppleTVOS11.4.sdk          iPhoneOS12.4.sdk
AppleTVOS12.4.sdk          iPhoneOS13.1.1.sdk
LICENSE.md                 iPhoneOS13.7.sdk
README.md                  iPhoneOS14.5.sdk
create_generic_symlinks.sh iPhoneOS14.8.sdk
create_patched_sdk.py      iPhoneOS15.5.sdk
create_patched_sdk.sh      iPhoneOS16.4.sdk
create_patched_sdk_tvos.sh iPhoneOS9.3.sdk
iPhoneOS10.3.sdk
```
```bash
$ ls $(xcode-select -p)/Platforms/iPhoneOS.platform/Developer/SDKs
iPhoneOS.sdk     iPhoneOS17.2.sdk
```

由上述结果可知，最新的 iOS SDK 版本为 17.2，它是 Xcode 15.1 的内置 SDK。而内置的公开 Public SDK 里通常是没有私有链接库 PrivateFrameworks 的。需要完整的 Full SDK 才行。

那么我们要怎么做呢？

## 解决方法

如果你只是需要解决这一个问题，那么解决方法很简单：把 **latest** 改成你 `$THEOS/sdks` 当中存在的版本，比如 `15.5`：

```
TARGET := iphone:clang:15.5:14.0
```

这样构建的时候就会选取 theos 打过补丁的 SDK，也就能找到 `BackBoardServices.tbd` 了。

## 如何获取 Full SDK 呢？

到这里你可能会有疑问了，`$THEOS/sdks` 当中的、打过补丁的 Full SDK 是从哪里来的呢？其实我们自己也能获取我们想要的任意版本的 Full SDK（iOS 17 除外）。

### 选取合适的 Xcode 版本

这很重要。首先你要理解一件事：**不同版本的 Xcode 内置的 SDK 版本是不同的，Xcode 与它内置的 SDK 版本最为匹配。** 即使 Xcode 能够兼容低一点儿或者高一点儿版本的 SDK，使用的时候也会出现各种奇葩问题。

1. 确定我们插件所需要支持的最低 iOS 版本，如 iOS 14.5。
2. 确定我们插件所能支持的最高 iOS 版本，如 iOS 17.0。
3. 安装 [xcodes](https://github.com/XcodesOrg/xcodes)，然后根据我们的 iOS 版本范围，找到对应的 Xcode 版本范围：
  - iOS 14.5 对应 Xcode 12.5.1
  - iOS 17.0 对应 Xcode 15.0.1
4. 在以上范围中选择一个你当前 macOS 版本下能稳定运行的 Xcode 版本，通常我们会选取大版本号当中的最后一个版本。我用的是 macOS Sonoma，所以我只能运行 Xcode 15。如果你用的是 macOS Ventura，我会推荐你使用 Xcode 14.3.1，它内置的 iOS SDK 版本为 16.4。
5. 安装推荐的 Xcode 版本，然后用 `sudo xcode-select -s /Applications/Xcode-14.3.1.app` 选取它作为默认工具链。

### 连接开发设备

我们需要打开 Xcode -> Window -> Devices and Simulators。然后把我们手头所有的测试、开发设备一个个连上去 —— 直到这些设备完成配对和开发所需的数据传输（不再转圈）为止。

为什么需要这一步呢？因为接下来我们需要这些设备的 Dyld 共享缓存去给 SDK 打补丁。

### 使用真机的 Dyld 共享缓存生成 Full SDK

首先我们需要编译并安装一个 [tbd](https://github.com/inoahdev/tbd)，这个工具能从原始二进制生成动态链接库插桩，即 `.tbd` 文件。

随后我们切换到 `$THEOS/sdks` 目录下，执行：

```bash
python3 create_patched_sdk.py -x $(dirname $(dirname $(xcode-select -p))) --tbd-path $(which tbd)
```

### 使用 Xcode 内置的模拟器 Dyld 共享缓存生成 Full SDK

执行：

```bash
python3 create_patched_sdk.py -x $(dirname $(dirname $(xcode-select -p))) --tbd-path $(which tbd) --use-simulator
```

完成上述步骤以后，你的 `$THEOS/sdks` 目录下应该包括了所有你手头所拥有的真机设备的 Full SDK，也包括你 Xcode 里内置模拟器的 Full SDK。可以愉快地进行开发了。

**Comment by qqwq122825** [comment]
感谢 已经从 https://github.com/xybp888/iOS-SDKs下载了几个sdk 版本 虽然还是有点点小问题 但是基本可以了
