### ISSUE TITLE
Is it possible to have the HUD in different positions in landscape and portrait?

### ISSUE THREAD

**Issue by CangWeiohh** [Lessica/TrollSpeed#25]
Is it possible to have the HUD in different positions in landscape and portrait?

**Comment by CangWeiohh** [comment]
> Yes. But it needs some additional refactor. There're too many options now.

Okay, thanks for your hard work.

**Comment by Lessica** [comment]
This feature is implemented in [v1.10.2](https://github.com/Lessica/TrollSpeed/releases/tag/v1.10.2). Give it a try!

**Comment by CangWeiohh** [comment]
> This feature is implemented in [v1.10.2](https://github.com/Lessica/TrollSpeed/releases/tag/v1.10.2). Give it a try!

Great, it's perfect for displaying in a different position in landscape!
