### ISSUE TITLE
使用自定义视图UITableViewController 的时候崩溃

### ISSUE THREAD

**Issue by qqwq122825** [Lessica/TrollSpeed#28]
我尝试在 HUDRootViewController下的  viewDidLoad 方法下里面 加入一个 UITableViewController视图 但是在上下滚动的时候 整个hud进程 被杀死 但是找不到崩溃日志  

- (void)viewDidLoad
{
    [super viewDidLoad];
...
 UITableViewController *tableView = [UITableViewController sharedInstance];
  tableView.view.frame=CGRectMake(10, 10, self.bounds.size.width-20, self.bounds.size.height-30);
  [self.view addSubview:tableView.view];
...

还有一个问题 我尝试获取一个 metai id<MTLDevice> device = MTLCreateSystemDefaultDevice(); device 返回的是一个null 不知道是不是巨魔的问题

**Comment by qqwq122825** [comment]
期待大佬的解答

**Comment by Lessica** [comment]
iOS 开发相关问题可以通过邮件联系我，付费解答哈。
