### ISSUE TITLE
TrollSpeed crashes / cannot open

### ISSUE THREAD

**Issue by lozhyol2** [Lessica/TrollSpeed#3]
TrollSpeed 1.8.2

iOS 16.1.1

TrollStore 2.0.8

TrollSpeed crashes / cannot open

**Comment by boli2017** [comment]
TrollSpeed 1.8.2
iPadOS 17.0
TrollStore 2.0.8
 cannot open too

**Comment by arandomdev** [comment]
I am also experiencing the same issue on iOS 16.6.1, iPhone X, TrollStore 2.0.8.

I tried to download the crashlogs with idevicecrashreport but it doesn't include it. I was able to get the syslogs that contain "hudapp" from launching the app to the end of the crash. Would that help?

[TrollSpeed Syslog.txt](https://github.com/Lessica/TrollSpeed/files/13534780/TrollSpeed.Syslog.txt)

**Comment by Lessica** [comment]
Try enable "Developer Mode".

**Comment by Lessica** [comment]
> I am also experiencing the same issue on iOS 16.6.1, iPhone X, TrollStore 2.0.8.
> 
> I tried to download the crashlogs with idevicecrashreport but it doesn't include it. I was able to get the syslogs that contain "hudapp" from launching the app to the end of the crash. Would that help?
> 
> [TrollSpeed Syslog.txt](https://github.com/Lessica/TrollSpeed/files/13534780/TrollSpeed.Syslog.txt)

Try enable "Developer Mode".

**Comment by arandomdev** [comment]
Yep that worked, thank you so much!
