### ISSUE TITLE
The project compiled with Xcode cannot display the network speed correctly

### ISSUE THREAD

**Issue by Simple-clear** [Lessica/TrollSpeed#30]
When compiled with Xcode 14, Trollspeed runs successfully in the Xcode Simulator environment under version 16.2. However, when installed on a device running version 15.6, the network speed is not displayed. The device has Trollstore installed, and the installation is performed using Trollstore. Subsequently, testing on an iOS 16.7 device also reveals the same issue
![Uploading a741f2ee1694f8aaf6dc14a537ab84a0.png…]()

**Comment by Lessica** [comment]
1. Screenshot is broken.
2. Re-try with Xcode 15.

**Comment by Lessica** [comment]
因为部署了自动化编译，不详细解答编译问题。自己看自动化构建脚本。
