### ISSUE TITLE
Auto-shrinking problem

### ISSUE THREAD

**Issue by crazyfires** [Lessica/TrollSpeed#31]
Hello developers, thank you for providing such an excellent tool, I am using it on my 14pro, my system version is 16.6, I am currently experiencing an issue that confuses me, when I open the TrollSpeed ​​app and select the larger The way it's displayed, it gets bigger, but then it shrinks automatically after about two seconds. I have bad eyesight. I hope you can fix this vulnerability. Thank you very much!

**Comment by Lessica** [comment]
Duplicate of #16
