### ISSUE TITLE
[Feature Request] Change Color of Text in Inverted Mode

### ISSUE THREAD

**Issue by 1ahmadbassam** [Lessica/TrollSpeed#34]
**Describe the solution you'd like**
Ability to change the text color to an arbitrary color in inverted mode. Preferably for the TS version.

**Additional context**
~Tried to take a screenshot, but doesn't look like TrollSpeed shows the network bar in screenshots.~
Nevermind, didn't realize that this is a feature. Here's a screenshot.
![photo_2024-03-07_16-32-59](https://github.com/Lessica/TrollSpeed/assets/34858431/91d8100f-b006-4819-9433-178c5f17aaa0)

**Comment by Lessica** [comment]
My opinion: Use Helium instead.

**Comment by 1ahmadbassam** [comment]
Helium drains my battery a lot and is much less optimized. (I am currently using it for the battery text for testing purposes). Besides, with eggNotch, the indicator fits in there perfectly save for the text color :)
There's no need for a full color picker, maybe an input field for a static hex color for the text on inverted mode?

**Comment by Lessica** [comment]
> Helium drains my battery a lot and is much less optimized. (I am currently using it for the battery text for testing purposes). Besides, with eggNotch, the indicator fits in there perfectly save for the text color :)
> 
> There's no need for a full color picker, maybe an input field for a static hex color for the text on inverted mode?

Ask the author of Helium for a better battery life. There's no where to add inputs in TrollSpeed.
