### ISSUE TITLE
那个显示模块经常消失

### ISSUE THREAD

**Issue by lipeiaiwo** [Lessica/TrollSpeed#35]
大佬有空可以研究下TrollRecorder的做法 在桌面添加个小组件 然后重启后都能正常拉起 https://github.com/Lessica/TrollRecorder

**Comment by Lessica** [comment]
我研究我自己？

**Comment by lipeiaiwo** [comment]
原来都是大佬开发的

**Comment by Lessica** [comment]
无意开源，拉起方案暂不公开。
