### ISSUE TITLE
M1芯片编译错误

### ISSUE THREAD

**Issue by qq1091192337** [Lessica/TrollSpeed#36]
系统版本：MacOS 14.4
Xcode版本：15.3
系统架构：M1 Arm64
编译报错：ld: building for 'iOS-simulator', but linking in dylib (/Users/lijiajun/Downloads/TrollSpeed/libraries/SpringBoardServices.tbd) built for 'iOS'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
求教大佬如何解决

**Comment by Lessica** [comment]
多学点英语比什么都强。
