### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by blahdy** [Lessica/TrollSpeed#38]
Hello. Not a programmer, just a tinkerer. 

While looking for solutions to replace tetherme I stumbled upon https://github.com/nneonneo/socks5-ios (even pinged the dev to add udp support).

My question is if it's possible to use the same underlying technique on trollstore devices that trollspeed uses to make socks5-ios work in background and never be pulled from memory? It is rather lighweight and works in the background, but still can be suspended. It is also very stable and has great performance compared to Pairvpn, allows multiple clients and doesn't isolate the remote local network. There's a myriad of clients for that including v2box for ios. 

If it is, then would that require a lot of coding or just a few lines?

Thank you.

**Comment by Lessica** [comment]
Emmmm.. Just a few lines. But impossible to tinkerer.
