### ISSUE TITLE
能不能改成设置网速悬浮层的坐标

### ISSUE THREAD

**Issue by gsons** [Lessica/TrollSpeed#4]
能不能改成设置网速悬浮层的坐标，感觉不够靠左；还有就是显示vpn的已建立连接的信息

**Comment by Lessica** [comment]
我希望将 TrollSpeed 打造成简单易用且精致的样子，不希望提供太多自定义选项，尤其是自定义坐标和自定义颜色等等；而显示 VPN 连接信息/显示XX信息并不在网速浮窗的功能范围内，如需添加可以自行修改源码编译。

**Comment by Lessica** [comment]
类似“能不能新增XX状态显示”的 Issue 可以不要再提了，需要的话请自行添加。
