### ISSUE TITLE
Can the display be a little bigger?

### ISSUE THREAD

**Issue by long848629974** [Lessica/TrollSpeed#6]

**Comment by Wenkay** [comment]
您好，我知悉后 第一时间，给您回复。
                                    Wenkay

**Comment by Lessica** [comment]
No. I designed TrollSpeed for the most. If you want TrollSpeed to be bigger, smaller, black, white, red, green or yellow, or at the left, right, or bottom of the screen. Just modify its source code and compile it by yourself.
