### ISSUE TITLE
Obstructing information

### ISSUE THREAD

**Issue by P76x** [Lessica/TrollSpeed#9]
"Hello, can you optimize for A11 devices? The current version is obstructing information, displaying on the status bar, to the left of the battery icon."

![06B9609A-9B0E-4B01-9D6D-4E1A231F000E](https://github.com/Lessica/TrollSpeed/assets/153827846/3fe2602c-f096-4d18-b9ce-ffcf8a0697db)

![15465955-8A32-4ECF-B6E6-B8C2A5E64EE1](https://github.com/Lessica/TrollSpeed/assets/153827846/b284b721-46da-403b-bcd9-531524bda6ac)

**Comment by Lessica** [comment]
Well, but we will always have jailbreaks for A11 devices. You deserve better jailbreak tweaks.
